CLASS zbp_r_t01_invoice DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_t01_invoice.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_r_t01_invoice IMPLEMENTATION.
ENDCLASS.
