CLASS zbp_c_t01_article DEFINITION
PUBLIC
ABSTRACT
FINAL
FOR BEHAVIOR OF zc_t01_article.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_c_t01_article IMPLEMENTATION.
ENDCLASS.
